---
elasticsearch_version: "9.0.0"
elasticsearch_http_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_heap_size: "4g"
elasticsearch_password: "ChangeMe123!"
elasticsearch_data_path: "/data1/elasticsearch"
base_directory: "/opt/network-sensors"
cert_directory: "{{ base_directory }}/certificates"
