---
all:
  hosts:
    sensor-node:
      ansible_host: 192.168.243.183
      ansible_connection: ssh
      ansible_user: rberent
      ansible_become: yes
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3
