---
- name: "DIR TASK 1: Create base directory structure"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_directory }}"
    - "{{ base_directory }}/elasticsearch"
    - "{{ base_directory }}/kibana"
    - "{{ base_directory }}/logstash"
    - "{{ base_directory }}/mongodb"
    - "{{ base_directory }}/suricata"
    - "{{ base_directory }}/zeek"
    - "{{ base_directory }}/arkime"
    - "{{ base_directory }}/rita"
    - "{{ base_directory }}/certificates"
  tags: ['directories']

- name: "DIR TASK 2: Create Elasticsearch data directory"
  file:
    path: "{{ elasticsearch_data_path }}"
    state: directory
    mode: '0755'
    owner: "1000"  # Elasticsearch user in container
    group: "1000"
  tags: ['directories']

- name: "DIR TASK 3: Create MongoDB data directory"
  file:
    path: "{{ mongodb_data_path }}"
    state: directory
    mode: '0755'
    owner: "999"  # MongoDB user in container
    group: "999"
  tags: ['directories']

- name: "DIR TASK 4: Create logs directory structure"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ logs_directory }}"
    - "{{ logs_directory }}/suricata"
    - "{{ logs_directory }}/zeek"
    - "{{ logs_directory }}/rita"
  tags: ['directories']

- name: "DIR TASK 5: Create Arkime PCAP directory"
  file:
    path: "{{ arkime_pcap_path }}"
    state: directory
    mode: '0755'
  tags: ['directories']

- name: Display directory structure
  debug:
    msg:
      - "Directory structure created:"
      - "  Base: {{ base_directory }}"
      - "  Elasticsearch data: {{ elasticsearch_data_path }}"
      - "  MongoDB data: {{ mongodb_data_path }}"
      - "  Logs: {{ logs_directory }}"
      - "  PCAPs: {{ arkime_pcap_path }}"
  tags: ['directories']
