---
- name: "TASK 1: Check if Docker is already installed"
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false
  tags: ['docker']

- name: Display current Docker status
  debug:
    msg: "Docker already installed: {{ docker_check.stdout }}"
  when: docker_check.rc == 0
  tags: ['docker']

- name: "TASK 2: Remove old Docker versions if present"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: docker_check.rc != 0
  tags: ['docker']

- name: "TASK 3: Create keyrings directory"
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: ['docker']

- name: "TASK 4: Download Docker GPG key"
  get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: /tmp/docker.gpg
    mode: '0644'
  register: gpg_download
  tags: ['docker']

- name: Display GPG key download status
  debug:
    msg: "Docker GPG key downloaded to /tmp/docker.gpg"
  when: gpg_download is changed
  tags: ['docker']

- name: "TASK 5: Convert and install Docker GPG key"
  shell: |
    gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  tags: ['docker']

- name: "TASK 6: Add Docker official repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  register: docker_repo
  tags: ['docker']

- name: Display repository addition status
  debug:
    msg: "Docker official repository added"
  when: docker_repo is changed
  tags: ['docker']

- name: "TASK 7: Update apt cache after adding Docker repo"
  apt:
    update_cache: yes
  when: docker_repo is changed
  tags: ['docker']

- name: "TASK 8: Install Docker CE and components"
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  register: docker_install
  tags: ['docker']

- name: Display Docker installation status
  debug:
    msg: "Docker CE installed: {{ docker_packages | join(', ') }}"
  when: docker_install is changed
  tags: ['docker']

- name: "TASK 9: Ensure Docker service is started and enabled"
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: ['docker']

- name: "TASK 10: Verify Docker installation"
  command: docker run --rm hello-world
  register: docker_test
  changed_when: false
  tags: ['docker', 'verify']

- name: Display Docker verification result
  debug:
    msg:
      - "Docker is working correctly!"
      - "{{ docker_test.stdout_lines[-1] }}"
  when: "'Hello from Docker!' in docker_test.stdout"
  tags: ['docker', 'verify']

- name: "TASK 11: Get Docker version"
  command: docker --version
  register: docker_version_output
  changed_when: false
  tags: ['docker']

- name: "TASK 12: Get Docker Compose version"
  command: docker compose version
  register: docker_compose_version
  changed_when: false
  tags: ['docker']

- name: Display versions
  debug:
    msg:
      - "Docker: {{ docker_version_output.stdout }}"
      - "Docker Compose: {{ docker_compose_version.stdout }}"
  tags: ['docker']

- name: "TASK 13: Add ansible user to docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: docker_group
  tags: ['docker']

- name: Display user group addition
  debug:
    msg: "User '{{ ansible_user }}' added to docker group. Re-login required for group changes to take effect."
  when: docker_group is changed
  tags: ['docker']

- name: "TASK 14: Reset SSH connection for group changes"
  meta: reset_connection
  when: docker_group is changed
  tags: ['docker']
