---
- name: "Step 7: Deploy Zeek Network Security Monitor"
  hosts: all
  become: yes
  
  vars:
    # Zeek variables
    base_directory: "/opt/network-sensors"
    logs_directory: "/data2/logs"
    zeek_log_path: "{{ logs_directory }}/zeek"
    zeek_version: "8.0.1"
    capture_interface: "eno4"
  
  tasks:
    - name: Display Zeek deployment phase
      debug:
        msg:
          - "=========================================="
          - "PHASE 7: ZEEK DEPLOYMENT"
          - "=========================================="
          - "Version: {{ zeek_version }}"
          - "Capture Interface: {{ capture_interface }}"
          - "Logs Directory: {{ zeek_log_path }}"
          - "=========================================="
      tags: ['always']

    - name: Include zeek role
      import_role:
        name: zeek
      tags: ['zk']

    - name: Display Zeek information
      debug:
        msg:
          - "=========================================="
          - "PHASE 7: COMPLETED"
          - "=========================================="
          - "Zeek is running!"
          - "Monitoring interface: {{ capture_interface }}"
          - "Logs: {{ zeek_log_path }}/current/"
          - "Docker Compose: {{ base_directory }}/zeek/docker-compose.yml"
          - ""
          - "View logs:"
          - "  docker logs -f zeek"
          - "  tail -f {{ zeek_log_path }}/current/conn.log"
          - "=========================================="
      tags: ['always']
