---
- name: "ZEEK TASK 1: Create Zeek directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_directory }}/zeek"
    - "{{ base_directory }}/zeek/packages"
    - "{{ zeek_log_path }}"
  tags: ['zeek']

- name: "ZEEK TASK 2: Deploy Zeek entrypoint script"
  template:
    src: zeek-entrypoint.sh.j2
    dest: "{{ base_directory }}/zeek/zeek-entrypoint.sh"
    mode: '0755'
  tags: ['zeek']

- name: "ZEEK TASK 3: Deploy local.zeek"
  template:
    src: local.zeek.j2
    dest: "{{ base_directory }}/zeek/local.zeek"
    mode: '0644'
  tags: ['zeek']

- name: "ZEEK TASK 4: Deploy docker-compose.yml"
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_directory }}/zeek/docker-compose.yml"
    mode: '0644'
  tags: ['zeek']

- name: "ZEEK TASK 5: Start Zeek"
  community.docker.docker_compose_v2:
    project_src: "{{ base_directory }}/zeek"
    state: present
  tags: ['zeek']

- name: "ZEEK TASK 6: Wait and check logs"
  wait_for:
    path: "{{ zeek_log_path }}/conn.log"
    timeout: 60
  tags: ['zeek']

- name: Display status
  debug:
    msg: "Zeek running! Logs: {{ zeek_log_path }}/"
  tags: ['zeek']
