---
- name: "ZEEK TASK 1: Create Zeek directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_directory }}/zeek"
    - "{{ base_directory }}/zeek/scripts"
    - "{{ zeek_log_path }}"
  tags: ['zeek', 'config']

- name: "ZEEK TASK 2: Deploy Zeek entrypoint script"
  template:
    src: zeek-entrypoint.sh.j2
    dest: "{{ base_directory }}/zeek/zeek-entrypoint.sh"
    mode: '0755'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 3: Deploy Zeek local.zeek script"
  template:
    src: local.zeek.j2
    dest: "{{ base_directory }}/zeek/scripts/local.zeek"
    mode: '0644'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 4: Deploy Zeek docker-compose.yml"
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_directory }}/zeek/docker-compose.yml"
    mode: '0644'
  tags: ['zeek', 'docker']

- name: "ZEEK TASK 5: Start Zeek container with JA4+"
  community.docker.docker_compose_v2:
    project_src: "{{ base_directory }}/zeek"
    state: present
  register: zeek_deploy
  tags: ['zeek', 'deploy']

- name: Display Zeek deployment status
  debug:
    msg: "Zeek container deployed with JA4+ on {{ capture_interface }}"
  when: zeek_deploy is changed
  tags: ['zeek']

- name: "ZEEK TASK 6: Wait for Zeek to start logging"
  wait_for:
    path: "{{ zeek_log_path }}/current/conn.log"
    timeout: 120
  tags: ['zeek', 'verify']

- name: "ZEEK TASK 7: Verify Zeek is running"
  command: docker ps --filter name=zeek --format "{{ '{{' }}.Status{{ '}}' }}"
  register: zeek_status
  changed_when: false
  tags: ['zeek', 'verify']

- name: Display Zeek status
  debug:
    msg: 
      - "Zeek status: {{ zeek_status.stdout }}"
      - "JA4+ fingerprinting enabled!"
      - "Check for JA4 logs in: {{ zeek_log_path }}/current/ja4*.log"
  tags: ['zeek', 'verify']
