---
- name: "ZEEK TASK 1: Create Zeek directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_directory }}/zeek"
    - "{{ base_directory }}/zeek/scripts"
    - "{{ base_directory }}/zeek/packages"
    - "{{ zeek_log_path }}"
  tags: ['zeek', 'config']

- name: "ZEEK TASK 2: Deploy Zeek entrypoint script"
  template:
    src: zeek-entrypoint.sh.j2
    dest: "{{ base_directory }}/zeek/zeek-entrypoint.sh"
    mode: '0755'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 3: Deploy zeekctl.cfg"
  template:
    src: zeekctl.cfg.j2
    dest: "{{ base_directory }}/zeek/zeekctl.cfg"
    mode: '0644'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 4: Deploy node.cfg with correct interface"
  template:
    src: node.cfg.j2
    dest: "{{ base_directory }}/zeek/node.cfg"
    mode: '0644'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 5: Deploy Zeek local.zeek script"
  template:
    src: local.zeek.j2
    dest: "{{ base_directory }}/zeek/scripts/local.zeek"
    mode: '0644'
  tags: ['zeek', 'config']

- name: "ZEEK TASK 6: Deploy Zeek docker-compose.yml"
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_directory }}/zeek/docker-compose.yml"
    mode: '0644'
  tags: ['zeek', 'docker']

- name: "ZEEK TASK 7: Start Zeek container with JA4+"
  community.docker.docker_compose_v2:
    project_src: "{{ base_directory }}/zeek"
    state: present
  register: zeek_deploy
  tags: ['zeek', 'deploy']

- name: Display Zeek deployment status
  debug:
    msg: "Zeek container deployed with JA4+ on {{ capture_interface }}"
  when: zeek_deploy is changed
  tags: ['zeek']

- name: "ZEEK TASK 8: Wait for Zeek to initialize"
  pause:
    seconds: 30
  tags: ['zeek', 'verify']

- name: "ZEEK TASK 9: Verify Zeek is running"
  command: docker exec zeek zeekctl status
  register: zeek_status
  changed_when: false
  failed_when: false
  tags: ['zeek', 'verify']

- name: Display Zeek status
  debug:
    msg: "{{ zeek_status.stdout_lines }}"
  tags: ['zeek', 'verify']
