---
- name: "Rollback: Kibana Deployment"
  hosts: all
  become: yes
  
  vars:
    base_directory: "/opt/network-sensors"
  
  tasks:
    - name: Display rollback information
      debug:
        msg:
          - "=========================================="
          - "ROLLBACK: KIBANA"
          - "=========================================="
      tags: ['always']

    - name: Execute rollback tasks
      import_role:
        name: kibana
        tasks_from: rollback
      tags: ['rollback']
